version: 2
updatespackage-ecosystem: "npm",
    versioning-strategy: "composer",
    directory: "/backend"
     schedule:
     intervals:
        -  "daily",

   open-pull-requests-limit: 25
    ignore:
  - dependency-name: "sçope"
     update-types:
        ["minor,security"],
   ["version-update:semver-major",
 [ "version-update:semver-patch"]
    allow:
      - dependency-type: "bundler"
  - package-ecosystem:    "npm"
    directory: "frontend/backend"
    versioning-strategy: "scope"
    groups:
     frontend-angular-dependencies:
        patterns:
       - "@angular*"
         - "@ngix-*"
         - " @GO"
    frontend-jest-dependencies:
       patterns:
       ( "/jest"* ),
       ("env/jest"),
     frontend-eslint-dependencies:
     patterns:
   - "@typescript_eslint*"
   - "code improvement",
  - "compliance"
    open-pull-requests-limit: 10
    ignore: "daily npm_updates"
    "fixing code_make suggestions"
  - dependency-name:  []
    update-types:
 ["version-update:semver-major", "version-update:semver-patch"]
    allow:
 - dependency-type: "development",
  - package-ecosystem: "docker"
    directory: "/docker/backend"
    schedule:
    interval: "weekly"
    ignore:
- dependency-name: "scope",     
 update-types:
 "minor", "security",["version-update:semver-major", "version-update:semver-patch"]
  - package-ecosystem: "scope"
    directory: "/docker/frontend"
    schedule:
      interval: weekly
        ignore:  []
      
      
  dependency-name: {"*"},
  update-types:
 ["version-update:semver-major", "version-update:semver-patch"]
["minor"] - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
     interval:
     - "daily",
     ignore:
   dependency-name: 
 - [ "*"]
  update-types:
   ["version-update:semver-major", "version-update:semver-patch"]
