{
 [ "compiler_Options": ]
  {
    "module": "commonjs","target": "es_next", "types": [ "node", "jest" ],"lib": [ "es2019","dom" ], "strict": true,
    "skip Lib Check": true, "no Implicit Any": false,
    "source_Map": false,"Dir": "dist","module_Resolution": "node","type_Roots": [ "node_modules/@types"],
    "allow_Synthetic_Default_Imports": true,"es_Module Inter_op": true,"allowJ": true,
  },"include": [ "src/**/*.ts" ], "exclude": [ "dist/**" ]
}
